export const CATALOG_LIST_REQUEST = 'CATALOG_LIST_REQUEST'
export const CATALOG_LIST_SUCCESS = 'CATALOG_LIST_SUCCESS'
export const CATALOG_LIST_FAIL = 'CATALOG_LIST_FAIL'

export const CATALOG_DETAILS_REQUEST = 'CATALOG_DETAILS_REQUEST'
export const CATALOG_DETAILS_SUCCESS = 'CATALOG_DETAILS_SUCCESS'
export const CATALOG_DETAILS_FAIL = 'CATALOG_DETAILS_FAIL'


export const FETCH_CATALOG_REQUEST = 'FETCH_CATALOG_REQUEST';
export const FETCH_CATALOG_SUCCESS = 'FETCH_CATALOG_SUCCESS';
export const FETCH_CATALOG_FAILURE = 'FETCH_CATALOG_FAILURE';