# Generated by Django 3.1.4 on 2023-12-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_typeproduct_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeproduct',
            name='_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
